# Generated by Django 2.2.1 on 2019-05-13 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190509_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lolaccountregistered',
            old_name='host',
            new_name='owner',
        ),
    ]
