# Generated by Django 2.2.1 on 2019-05-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20190513_0326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lolaccountregistered',
            old_name='LoLid',
            new_name='AccountId',
        ),
    ]
