# Generated by Django 2.2.1 on 2019-05-13 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20190513_0637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lolaccountregistered',
            old_name='AccountId',
            new_name='account_id',
        ),
    ]
